steps:

- task: Npm@1
  displayName: npm install

- task: Gulp@0
  inputs:
    publishJUnitResults: "true"
  displayName: Gulp

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)
    ArtifactName: "drop"
    ArtifactType: "Container"
  displayName: Publish the artifacts
